application: twitalkerplus
version: 1
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:
- url: /
  script: web.py

- url: /_wave/robot/profile
  script: web.py

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  expiration: 7d
  mime_type: image/vnd.microsoft.icon

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  expiration: 7d

- url: /cron\d+
  script: cron.py
  login: admin

- url: /_ah/xmpp/message/chat/
  script: xmpp.py
  login: admin

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
